### ISSUE TITLE
Gestures inside of _buildContent are not recognized on first interaction

### ISSUE THREAD

**Issue by kamami** [ricnaaru/scrollable_bottom_sheet#10] opened 2019-06-07 14:24 UTC
When tapping a button inside the _buildContent, the gesture is not fired! You need to tap it again, to see the expected result.

**Comment by ricnaaru** [comment] 2019-06-14 15:21
are you using the latest version? because this should be fixed already..

**Comment by tp** [comment] 2019-06-17 09:15
@ricnaaru Would you mind explaining what the root cause was / and how you fixed it? I was seeing the same in an adapted version of the draggable scrollable sheet from Flutter and probably ran into the same issue.

**Comment by ricnaaru** [comment] 2019-06-17 10:00
#7 i suspected this what's happening, but if the bug is still occurs if you're using the latest version, please provide the steps to reproduce.. thanks

**Comment by ricnaaru** [comment] 2019-06-20 09:28
i'm sorry that i forgot to roll the pull request to pub dev, 0.2.2 should fix the bug.. thanks for your report

**Closed as completed by ricnaaru** 2019-06-20 09:28 UTC
